# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2021_06_03_061750) do

  create_table "printers", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "name"
    t.string "manufacturer"
    t.string "model"
    t.text "modifications"
    t.text "notes"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_printers_on_user_id"
  end

  create_table "prints", force: :cascade do |t|
    t.integer "user_id", null: false
    t.text "settings"
    t.string "file"
    t.boolean "success"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "spool_id"
    t.string "print_name"
    t.text "description"
    t.text "notes"
    t.index ["spool_id"], name: "index_prints_on_spool_id"
    t.index ["user_id"], name: "index_prints_on_user_id"
  end

  create_table "prusa_settings_filaments", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "bed_temperature"
    t.string "bridge_fan_speed"
    t.string "compatible_printers"
    t.string "compatible_printers_condition"
    t.string "compatible_prints"
    t.string "compatible_prints_condition"
    t.string "cooling"
    t.string "disable_fan_first_layers"
    t.string "end_filament_gcode"
    t.string "extrusion_multiplier"
    t.string "fan_always_on"
    t.string "fan_below_layer_time"
    t.string "filament_colour"
    t.string "filament_cooling_final_speed"
    t.string "filament_cooling_initial_speed"
    t.string "filament_cooling_moves"
    t.string "filament_cost"
    t.string "filament_density"
    t.string "filament_deretract_speed"
    t.string "filament_diameter"
    t.string "filament_load_time"
    t.string "filament_loading_speed"
    t.string "filament_loading_speed_start"
    t.string "filament_max_volumetric_speed"
    t.string "filament_minimal_purge_on_wipe_tower"
    t.string "filament_notes"
    t.string "filament_ramming_parameters"
    t.string "filament_retract_before_travel"
    t.string "filament_retract_before_wipe"
    t.string "filament_retract_layer_change"
    t.string "filament_retract_length"
    t.string "filament_retract_lift"
    t.string "filament_retract_lift_above"
    t.string "filament_retract_lift_below"
    t.string "filament_retract_restart_extra"
    t.string "filament_retract_speed"
    t.string "filament_settings_id"
    t.string "filament_soluble"
    t.string "filament_spool_weight"
    t.string "filament_toolchange_delay"
    t.string "filament_type"
    t.string "filament_unload_time"
    t.string "filament_unloading_speed"
    t.string "filament_unloading_speed_start"
    t.string "filament_vendor"
    t.string "filament_wipe"
    t.string "first_layer_bed_temperature"
    t.string "first_layer_temperature"
    t.string "full_fan_speed_layer"
    t.string "inherits"
    t.string "max_fan_speed"
    t.string "min_fan_speed"
    t.string "min_print_speed"
    t.string "slowdown_below_layer_time"
    t.string "start_filament_gcode"
    t.string "temperature"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_prusa_settings_filaments_on_user_id"
  end

  create_table "prusa_settings_printers", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "bed_custom_model"
    t.string "bed_custom_texture"
    t.string "bed_shape"
    t.string "before_layer_gcode"
    t.string "between_objects_gcode"
    t.string "color_change_gcode"
    t.string "cooling_tube_length"
    t.string "cooling_tube_retraction"
    t.string "default_filament_profile"
    t.string "default_print_profile"
    t.string "deretract_speed"
    t.string "end_gcode"
    t.string "extra_loading_move"
    t.string "extruder_colour"
    t.string "extruder_offset"
    t.string "gcode_flavor"
    t.string "high_current_on_filament_swap"
    t.string "host_type"
    t.string "inherits"
    t.string "layer_gcode"
    t.string "machine_limits_usage"
    t.string "machine_max_acceleration_e"
    t.string "machine_max_acceleration_extruding"
    t.string "machine_max_acceleration_retracting"
    t.string "machine_max_acceleration_x"
    t.string "machine_max_acceleration_y"
    t.string "machine_max_acceleration_z"
    t.string "machine_max_feedrate_e"
    t.string "machine_max_feedrate_x"
    t.string "machine_max_feedrate_y"
    t.string "machine_max_feedrate_z"
    t.string "machine_max_jerk_e"
    t.string "machine_max_jerk_x"
    t.string "machine_max_jerk_y"
    t.string "machine_max_jerk_z"
    t.string "machine_min_extruding_rate"
    t.string "machine_min_travel_rate"
    t.string "max_layer_height"
    t.string "max_print_height"
    t.string "min_layer_height"
    t.string "nozzle_diameter"
    t.string "parking_pos_retraction"
    t.string "pause_print_gcode"
    t.string "print_host"
    t.string "printer_model"
    t.string "printer_notes"
    t.string "printer_settings_id"
    t.string "printer_technology"
    t.string "printer_variant"
    t.string "printer_vendor"
    t.string "printhost_apikey"
    t.string "printhost_cafile"
    t.string "remaining_times"
    t.string "retract_before_travel"
    t.string "retract_before_wipe"
    t.string "retract_layer_change"
    t.string "retract_length"
    t.string "retract_length_toolchange"
    t.string "retract_lift"
    t.string "retract_lift_above"
    t.string "retract_lift_below"
    t.string "retract_restart_extra"
    t.string "retract_restart_extra_toolchange"
    t.string "retract_speed"
    t.string "silent_mode"
    t.string "single_extruder_multi_material"
    t.string "start_gcode"
    t.string "template_custom_gcode"
    t.string "thumbnails"
    t.string "toolchange_gcode"
    t.string "use_firmware_retraction"
    t.string "use_relative_e_distances"
    t.string "use_volumetric_e"
    t.string "variable_layer_height"
    t.string "wipe"
    t.string "z_offset"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_prusa_settings_printers_on_user_id"
  end

  create_table "prusa_settings_prints", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "avoid_crossing_perimeters"
    t.string "avoid_crossing_perimeters_max_detour"
    t.string "bottom_fill_pattern"
    t.string "bottom_solid_layers"
    t.string "bottom_solid_min_thickness"
    t.string "bridge_acceleration"
    t.string "bridge_angle"
    t.string "bridge_flow_ratio"
    t.string "bridge_speed"
    t.string "brim_width"
    t.string "clip_multipart_objects"
    t.string "compatible_printers"
    t.string "compatible_printers_condition"
    t.string "complete_objects"
    t.string "default_acceleration"
    t.string "dont_support_bridges"
    t.string "draft_shield"
    t.string "elefant_foot_compensation"
    t.string "ensure_vertical_shell_thickness"
    t.string "external_perimeter_extrusion_width"
    t.string "external_perimeter_speed"
    t.string "external_perimeters_first"
    t.string "extra_perimeters"
    t.string "extruder_clearance_height"
    t.string "extruder_clearance_radius"
    t.string "extrusion_width"
    t.string "fill_angle"
    t.string "fill_density"
    t.string "fill_pattern"
    t.string "first_layer_acceleration"
    t.string "first_layer_extrusion_width"
    t.string "first_layer_height"
    t.string "first_layer_speed"
    t.string "gap_fill_speed"
    t.string "gcode_comments"
    t.string "gcode_label_objects"
    t.string "infill_acceleration"
    t.string "infill_anchor"
    t.string "infill_anchor_max"
    t.string "infill_every_layers"
    t.string "infill_extruder"
    t.string "infill_extrusion_width"
    t.string "infill_first"
    t.string "infill_only_where_needed"
    t.string "infill_overlap"
    t.string "infill_speed"
    t.string "inherits"
    t.string "interface_shells"
    t.string "ironing"
    t.string "ironing_flowrate"
    t.string "ironing_spacing"
    t.string "ironing_speed"
    t.string "ironing_type"
    t.string "layer_height"
    t.string "max_print_speed"
    t.string "max_volumetric_speed"
    t.string "min_skirt_length"
    t.string "notes"
    t.string "only_retract_when_crossing_perimeters"
    t.string "ooze_prevention"
    t.string "output_filename_format"
    t.string "overhangs"
    t.string "perimeter_acceleration"
    t.string "perimeter_extruder"
    t.string "perimeter_extrusion_width"
    t.string "perimeter_speed"
    t.string "perimeters"
    t.string "post_process"
    t.string "print_settings_id"
    t.string "raft_layers"
    t.string "resolution"
    t.string "seam_position"
    t.string "single_extruder_multi_material_priming"
    t.string "skirt_distance"
    t.string "skirt_height"
    t.string "skirts"
    t.string "slice_closing_radius"
    t.string "small_perimeter_speed"
    t.string "solid_infill_below_area"
    t.string "solid_infill_every_layers"
    t.string "solid_infill_extruder"
    t.string "solid_infill_extrusion_width"
    t.string "solid_infill_speed"
    t.string "spiral_vase"
    t.string "standby_temperature_delta"
    t.string "support_material"
    t.string "support_material_angle"
    t.string "support_material_auto"
    t.string "support_material_buildplate_only"
    t.string "support_material_contact_distance"
    t.string "support_material_enforce_layers"
    t.string "support_material_extruder"
    t.string "support_material_extrusion_width"
    t.string "support_material_interface_contact_loops"
    t.string "support_material_interface_extruder"
    t.string "support_material_interface_layers"
    t.string "support_material_interface_spacing"
    t.string "support_material_interface_speed"
    t.string "support_material_pattern"
    t.string "support_material_spacing"
    t.string "support_material_speed"
    t.string "support_material_synchronize_layers"
    t.string "support_material_threshold"
    t.string "support_material_with_sheath"
    t.string "support_material_xy_spacing"
    t.string "thin_walls"
    t.string "threads"
    t.string "top_fill_pattern"
    t.string "top_infill_extrusion_width"
    t.string "top_solid_infill_speed"
    t.string "top_solid_layers"
    t.string "top_solid_min_thickness"
    t.string "travel_speed"
    t.string "wipe_tower"
    t.string "wipe_tower_bridging"
    t.string "wipe_tower_no_sparse_layers"
    t.string "wipe_tower_rotation_angle"
    t.string "wipe_tower_width"
    t.string "wipe_tower_x"
    t.string "wipe_tower_y"
    t.string "xy_size_compensation"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_prusa_settings_prints_on_user_id"
  end

  create_table "spools", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "rfid"
    t.string "material"
    t.string "manufacturer"
    t.date "purchased"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_spools_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "printers", "users"
  add_foreign_key "prints", "spools"
  add_foreign_key "prints", "users"
  add_foreign_key "prusa_settings_filaments", "users"
  add_foreign_key "prusa_settings_printers", "users"
  add_foreign_key "prusa_settings_prints", "users"
  add_foreign_key "spools", "users"
end
